// The Novel — factoid bank
// ~210 facts across literature, theoretical physics, and history.
// Chosen to be rabbit-hole-shaped: specific, strange, and good for sparking a scene.
// Edit freely — just keep the array structure.

const FACTS = [
  // ============ LITERATURE ============
  "Kafka asked his friend Max Brod to burn all his manuscripts after his death. Brod refused. That refusal is why we have The Trial, The Castle, and Amerika — every one published posthumously, against the author's explicit wish.",
  "Borges wrote 'The Library of Babel' before he went fully blind. By the time he was director of the National Library of Argentina, he could no longer read its books — he called it God's irony, 'books and night' given at once.",
  "Moby-Dick sold 3,215 copies in Melville's lifetime and was effectively forgotten. He died in 1891 working as a customs inspector; the novel was rediscovered in the 1920s, decades too late for him to know.",
  "Dante invented words. Roughly a thousand Italian terms appear for the first time in the Divine Comedy, and the modern standard Italian language owes its shape substantially to a poem about hell written in exile.",
  "Mary Shelley wrote Frankenstein at 18, during the 'Year Without a Summer' at Lake Geneva, in a ghost-story contest with Byron and Percy Shelley. The bad weather was caused by a volcanic eruption in Indonesia the year before.",
  "The original draft of 1984 was titled 'The Last Man in Europe'. Orwell's publisher pushed for the change. He finished it dying of tuberculosis on the Scottish island of Jura, typing in bed.",
  "The Epic of Gilgamesh is older than the Iliad by roughly 1,500 years and contains a flood narrative — a man told to build a boat and save life from a divine deluge — that predates the one in Genesis.",
  "Emily Dickinson published fewer than a dozen of her nearly 1,800 poems while alive. Her sister found the rest in a locked chest after her death, hand-sewn into small booklets Dickinson called 'fascicles'.",
  "Proust's 'In Search of Lost Time' was rejected by the first publisher he sent it to — André Gide, reading for Gallimard, turned it down and later called it the worst mistake of his life.",
  "The longest sentence in published English literature runs over 13,000 words, in Jonathan Coe's 'The Rotters' Club'. Molly Bloom's closing soliloquy in Ulysses is the more famous contender at around 4,000.",
  "Bram Stoker's Dracula is written entirely as letters, diary entries, telegrams, and newspaper clippings — there is no narrator. The form was meant to make the supernatural feel like documented fact.",
  "The Brontë sisters first published under male pseudonyms — Currer, Ellis, and Acton Bell — keeping their own initials. Charlotte said they feared critics would judge women's writing 'with prejudice'.",
  "Tolkien spent more time inventing Elvish languages than writing the plot of The Lord of the Rings. He said the stories existed primarily to give his invented languages a world to be spoken in.",
  "Agatha Christie disappeared for eleven days in 1926. Her car was found abandoned; a nationwide search followed. She was found at a spa hotel, registered under the surname of her husband's mistress, and never explained what happened.",
  "The Voynich manuscript, a 15th-century book written in an unknown script in an unknown language, has resisted every cryptographer, linguist, and codebreaker for over a century. No one knows if it means anything at all.",
  "Herman Melville and Nathaniel Hawthorne were neighbours in the Berkshires. Melville fell into an intense friendship with Hawthorne while writing Moby-Dick and dedicated the book to him; the relationship cooled soon after, for reasons unknown.",
  "Virginia Woolf wrote standing up at a tall desk, partly in competition with her sister Vanessa, who stood to paint. She wanted, she said, to know what the painter felt.",
  "The first novel in English by a known woman is often considered to be Aphra Behn's 'Oroonoko' (1688). Behn had earlier worked as a spy for Charles II in Antwerp, under the code name Astrea.",
  "Samuel Beckett was stabbed in Paris in 1938 by a pimp named Prudent. Recovering in hospital, he was visited by Suzanne Dumesnil, who became his lifelong partner. He later asked his attacker why; the man replied, 'I don't know, sir.'",
  "Dostoevsky was sentenced to death in 1849 and stood before a firing squad. The execution was a staged mock; a reprieve was read out at the last moment. He spent the next four years in a Siberian prison camp.",
  "Gabriel García Márquez wrote 'One Hundred Years of Solitude' in eighteen months, selling his car to fund the time. When he finished, he reportedly didn't have enough money to mail the whole manuscript and sent the second half first.",
  "The word 'serendipity' was coined by Horace Walpole in 1754, from a Persian fairy tale, 'The Three Princes of Serendip', whose heroes were always making discoveries by accident and sagacity.",
  "Jane Austen published all her novels anonymously — the title pages read only 'By a Lady'. She earned around £600 in her lifetime from her writing and never saw her name on a book.",
  "Shakespeare's 'Cardenio', a play co-written with John Fletcher and performed in 1613, is completely lost. Its existence is documented but no text survives — one of the great holes in the English canon.",
  "The manuscript of T.S. Eliot's 'The Waste Land' was edited so heavily by Ezra Pound that Pound cut it almost in half. Eliot dedicated the poem to him as 'il miglior fabbro' — the better craftsman.",
  "Marcel Proust lined his bedroom with cork to block out noise and wrote most of his great novel in bed, at night, increasingly reclusive, as his asthma and the manuscript both consumed him.",
  "Charlotte Perkins Gilman wrote 'The Yellow Wallpaper' (1892) after a 'rest cure' for depression nearly drove her mad. She sent a copy to the doctor who prescribed it. He never replied, but reportedly changed his methods.",
  "The Icelandic sagas were written down in the 13th century but describe events from the 9th and 10th. They are among the only medieval European literature written in prose, not verse, and in the vernacular rather than Latin.",
  "Mikhail Bulgakov burned the first manuscript of 'The Master and Margarita' in 1930. He rewrote it from memory; the novel, with its famous line 'manuscripts don't burn', wasn't published until 1966, decades after his death.",
  "Lord Byron's memoirs were burned by his publisher and friends in a fireplace at John Murray's office in 1824, weeks after his death — judged too scandalous to survive. No copy was kept. Their contents are lost forever.",
  "Anne Frank revised her own diary. Having heard a radio broadcast urging Dutch citizens to keep wartime records, she began rewriting earlier entries with an eye to eventual publication — editing herself as a future author.",
  "The 'Q source' is a hypothetical lost document that scholars infer must have existed, because Matthew and Luke share material absent from Mark. No copy has ever been found; it is reconstructed entirely from inference.",
  "Vladimir Nabokov wrote his novels on index cards, which let him compose scenes out of order and shuffle them. The cards for his unfinished last novel were preserved against his instruction to destroy them.",
  "Flann O'Brien's 'The Third Policeman' was rejected and went unpublished in his lifetime; he told friends the manuscript had been lost on a train. It was published in 1967, a year after his death. It had been in a drawer the whole time.",
  "Sylvia Plath's only novel, 'The Bell Jar', was published under the pseudonym Victoria Lucas in January 1963, one month before her death. She didn't want her mother to recognise the autobiographical content.",
  "The oldest known named author in human history is Enheduanna, a Sumerian high priestess of around 2300 BCE. She wrote hymns to the goddess Inanna and signed them — a thousand years before Homer.",
  "Raymond Carver's spare, minimalist style may partly belong to his editor Gordon Lish, who cut some stories by more than half. The debate over how much of 'Carver' is Lish remains unresolved among scholars.",
  "Lewis Carroll's real name was Charles Dodgson, an Oxford mathematician who lectured on logic and geometry. 'Alice in Wonderland' is laced with mathematical jokes most readers never notice.",
  "James Joyce's 'Finnegans Wake' took seventeen years to write and is composed in a dream-language drawing on roughly sixty languages. Joyce said it was meant to reproduce the logic of the sleeping mind.",
  "Harper Lee published 'To Kill a Mockingbird' in 1960 and then almost nothing for the rest of her life. 'Go Set a Watchman', released in 2015, was actually an earlier draft of the same material, not a sequel.",
  "The 1,001 nights of the Arabian Nights frame is a stay of execution: Scheherazade tells her king a story each night, stopping at dawn on a cliffhanger, so he postpones her death to hear the ending. Storytelling as literal survival.",

  // ============ THEORETICAL PHYSICS & COSMOLOGY ============
  "Time runs measurably faster at your head than at your feet. Gravity slows time, and your head is slightly further from Earth's mass. The effect is tiny but has been measured with clocks just a foot apart.",
  "There is more empty space inside an atom than matter. If a hydrogen atom were scaled to the size of a football stadium, the nucleus would be a pea at the centre and the electron a speck in the stands.",
  "The cosmic microwave background — the faint afterglow of the Big Bang — is part of the static you once saw on an untuned analogue television. You were watching the early universe.",
  "Quantum entanglement was proposed by Einstein and two colleagues in 1935 as a thought experiment meant to expose quantum mechanics as absurd. He called it 'spooky action at a distance'. It has since been confirmed experimentally many times.",
  "The Planck length, about 1.6 × 10⁻³⁵ metres, may be the smallest length that has any physical meaning. Below it, our concepts of distance and space appear to stop working entirely.",
  "Black holes evaporate. Through a process predicted by Stephen Hawking, they slowly radiate energy and shrink. A black hole the mass of the sun would take around 10⁶⁷ years to disappear — vastly longer than the current age of the universe.",
  "The universe is not just expanding but expanding faster over time. The cause is called 'dark energy', a placeholder name for something that makes up roughly 68% of everything and which no one understands.",
  "In the double-slit experiment, a single particle fired at two slits behaves as if it passes through both at once — unless you measure which slit it took, at which point it picks one. Observation changes the outcome.",
  "A teaspoon of neutron-star material would weigh roughly six billion tonnes on Earth. The matter is so compressed that the protons and electrons have been crushed together into neutrons.",
  "According to relativity, there is no universal 'now'. Two events that are simultaneous for one observer can happen in a definite order for another moving differently. Simultaneity is not absolute — it depends on motion.",
  "If you fell into a large black hole, an outside observer would see you slow down and freeze at the edge, reddening and fading forever, never quite crossing. From your own point of view, you would cross in moments.",
  "Antimatter is real and routinely made in labs. When a particle meets its antiparticle, both annihilate into pure energy. A persistent mystery is why the universe is made of matter at all, when the Big Bang should have made equal amounts of both.",
  "Schrödinger devised his famous cat thought experiment in 1935 to mock the idea of quantum superposition — he found a cat both alive and dead ridiculous. The example meant as a reductio became the most famous image in quantum physics.",
  "Light has no rest mass and always travels at the same speed in a vacuum, regardless of how fast you move toward or away from its source. This single stubborn fact is the seed of Einstein's entire theory of special relativity.",
  "Olbers' paradox asks why the night sky is dark. If the universe were infinite, eternal, and full of stars, every line of sight should end on a star and the whole sky should blaze. The darkness is evidence the universe had a beginning.",
  "Quantum tunnelling lets particles pass through barriers they classically shouldn't be able to cross. It is not a curiosity — it is why the sun shines, allowing protons to fuse despite their mutual repulsion.",
  "The arrow of time may come down to statistics. The laws of physics work the same forwards and backwards, yet eggs don't unscramble. The difference is that disordered states vastly outnumber ordered ones — time's direction is a counting problem.",
  "Heisenberg's uncertainty principle isn't about clumsy measurement. It says a particle simply does not possess both a precise position and a precise momentum at once. The indeterminacy is in nature, not in the instrument.",
  "There may be more than three spatial dimensions, curled up too small to see. String theory typically requires ten or eleven dimensions for its mathematics to be consistent — most of them hidden at scales near the Planck length.",
  "The observable universe is about 93 billion light-years across, even though it is only 13.8 billion years old. Space itself has been expanding, carrying distant galaxies far beyond where light alone could have reached.",
  "Feynman's 'sum over histories' approach says a particle travelling from A to B takes every possible path simultaneously, including absurd detours to distant galaxies. The paths interfere, and the familiar straight line is what survives.",
  "The total electric charge of the universe appears to be exactly zero, and the total energy may be too — the positive energy of matter balanced by the negative energy of gravity. The universe may be, in a real sense, free.",
  "Atomic clocks are now so precise that they can detect the time difference caused by raising the clock a single centimetre. Relativity, once exotic, is now an engineering tolerance.",
  "Wolfgang Pauli predicted the neutrino in 1930 to save the conservation of energy, calling it 'a desperate remedy' and apologising for proposing a particle he thought could never be detected. It was found 26 years later.",
  "The information that falls into a black hole may not be destroyed, despite appearances. The 'black hole information paradox' pits quantum mechanics against general relativity and remains one of physics' deepest unresolved conflicts.",
  "There is a temperature so low — absolute zero — that all classical motion stops, but it can never quite be reached. Quantum mechanics guarantees a residual 'zero-point' jitter that no cooling can remove.",
  "Gravitational waves — ripples in spacetime itself — were predicted by Einstein in 1916 and first directly detected in 2015, from two black holes colliding over a billion light-years away. The detectors measured a shift smaller than a proton's width.",

  // ============ HISTORY ============
  "The Byzantine emperor Justinian II had his nose cut off when he was deposed in 695. He returned to the throne a decade later wearing a solid gold prosthetic — and took bloody revenge on those who had mutilated him.",
  "Genghis Khan's tomb has never been found. The soldiers who buried him are said to have killed everyone they met on the way back, then been killed in turn, so that no one alive knew the location.",
  "The shortest war in recorded history, the Anglo-Zanzibar War of 1896, lasted somewhere between 38 and 45 minutes. The Sultan's palace was shelled into surrender before the morning was out.",
  "The Aztec capital Tenochtitlan, built on an island in a lake, had a population of perhaps 200,000 around 1500 — larger than any city in Europe at the time except possibly Paris, with causeways, aqueducts, and floating gardens.",
  "The 'Year Without a Summer', 1816, was caused by the eruption of Mount Tambora the year before. Crops failed across the Northern Hemisphere, and the gloom indirectly produced Frankenstein and the invention of the bicycle.",
  "The Library of Ashurbanipal at Nineveh, destroyed by fire in 612 BCE, survived because the blaze baked its clay tablets hard rather than destroying them. Most of what we know of Mesopotamian literature comes from that accidental kiln.",
  "Hatshepsut, one of Egypt's most successful pharaohs, was systematically chiselled out of her monuments by her successor. The erasure was so incomplete that modern Egyptologists were able to reconstruct her reign from what remained.",
  "The first recorded labour strike happened in Egypt around 1152 BCE, when tomb-builders at Deir el-Medina downed tools over late rations. We have the records because they were written on stone.",
  "Iceland's parliament, the Althing, was founded around 930 CE on a windswept plain at Þingvellir and is among the oldest functioning legislative assemblies on Earth — older than almost every modern nation.",
  "The Antikythera mechanism, recovered from a Roman-era shipwreck, is a geared analogue computer roughly 2,100 years old that modelled the movements of the sun, moon, and planets. Nothing of comparable sophistication appears again for over a thousand years.",
  "Diogenes the Cynic lived in a large ceramic jar in Athens, owned almost nothing, and when Alexander the Great offered him any favour he wished, asked only that the conqueror stop blocking his sunlight.",
  "The 'turning a blind eye' phrase comes from Admiral Nelson at the Battle of Copenhagen in 1801. Ordered to withdraw, he raised the telescope to his blind eye, said he saw no signal, and pressed the attack to victory.",
  "Cleopatra lived closer in time to the first Moon landing than to the building of the Great Pyramid. The pyramid was already more than two thousand years old when she was born.",
  "Manichaeism, founded in 3rd-century Persia, was once a world religion stretching from Spain to China, with millions of followers. It was so thoroughly suppressed that for centuries it was known only through its enemies' descriptions.",
  "The Venetian Republic ran a state-controlled date for plague isolation: ships had to wait forty days — quaranta giorni — before landing. The word 'quarantine' is a fossil of that policy.",
  "In 1788, a sentry at the Battle of Karánsebes reportedly triggered a panic in which the Austrian army attacked itself in the dark, suffering thousands of casualties before the enemy Ottomans even arrived. The story is likely exaggerated but rooted in a real chaotic retreat.",
  "The Great Emu War of 1932 was a real military operation. The Australian army deployed soldiers with machine guns against destructive emu flocks in Western Australia — and effectively lost. The emus scattered and survived.",
  "Pheasant Island, a tiny river island between France and Spain, switches sovereignty every six months under a treaty signed in 1659. It is the smallest condominium in the world and has changed hands peacefully for over 350 years.",
  "The Cyrus Cylinder, from 539 BCE, records the Persian king's policy of returning displaced peoples and restoring their temples. It is sometimes called the first charter of human rights, though scholars debate how modern that reading is.",
  "Roman concrete is in some ways more durable than modern concrete, especially in seawater. It used volcanic ash that triggers ongoing chemical reactions, letting the material self-heal cracks over centuries. The recipe was effectively lost for over a millennium.",
  "The longest reign in recorded history may belong to Pepi II of Egypt, said to have ruled for around 90 years after taking the throne as a child around 2278 BCE — though the figure is disputed.",
  "The 'defenestration of Prague' in 1618 — throwing royal officials out of a castle window — he
